name: meeting_maker
description: Make meetings with ease

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  calendarro: ^1.0.0
  date_range_picker: ^1.0.6
  firebase_database: ^3.0.5
  random_string: ^1.1.0
  google_sign_in: ^4.0.6
  firebase_auth: ^0.14.0
  share: ^0.6.2+1
  md2_tab_indicator: ^1.0.2
  flutter_time_picker_spinner: ^1.0.5
  intl: ^0.15.8
  page_view_indicators: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf

    - family: Lobster
      fonts:
        - asset: fonts/Lobster-Regular.ttf

    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
        - asset: fonts/RobotoMono-RegularItalic.ttf
          style: italic

        - asset: fonts/RobotoMono-Bold.ttf
          weight: 700
        - asset: fonts/RobotoMono-BoldItalic.ttf
          weight: 700
          style: italic

        - asset: fonts/RobotoMono-Light.ttf
        - asset: fonts/RobotoMono-LightItalic.ttf
          style: italic

        - asset: fonts/RobotoMono-Thin.ttf
        - asset: fonts/RobotoMono-ThinItalic.ttf
          style: italic

        - asset: fonts/RobotoMono-Medium.ttf
        - asset: fonts/RobotoMono-MediumItalic.ttf
          style: italic

  uses-material-design: true
